export const ADD_EMPLOYEE_ACTION = "ADD_EMPLOYEE_ACTION";
export const DEPT_ID = "DEPT_ID";
export const EMP_COUNT = "EMP_COUNT";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const ADD_DEPERTMENT = "ADD_DEPERTMENT";
export const DELETE_MULTIPLE_EMP = "DELETE_MULTIPLE_EMP";
